version: '3.8'

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn run build && yarn run start"
    user: 0:0
